name: Check comment status
on:
  issue_comment:
    types: [edited]
    
    jobs:
      Check-Comments:
        runs-on: ubuntu-latest
        steps:
        uses: peter-evans/find-comment@v2
        id: fc
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'github-actions[bot]'
          body-includes: This comment was written by a bot!
